### ISSUE TITLE
API key is not stored

### ISSUE THREAD

**Issue by igorrust** [stuomas/bridge-map-view#1]
When entering an unrestricted API key and clicking "Go!", the input-field is cleared and nothing happens. 

I'm using Adobe Bridge 12 on Windows 10, I've copied all files as described, enabled debug mode (CSXS.11), and created a new unrestricted API key,

Is there any way on seeing why it's not accepted?

**Comment by igorrust** [comment]
> When entering an unrestricted API key and clicking "Go!", the input-field is cleared and nothing happens.
> 
> I'm using Adobe Bridge 12 on Windows 7, I've copied all files as described, enabled debug mode (CSXS.11), and created a new unrestricted API key,
> 
> Is there any way on seeing why it's not accepted?

Ok, answering my own question: I originally put the extension in the System extension folder (`C:\Program Files (x86)\Common Files\Adobe\CEP\extensions`). However, Bridge didn't have rights to create the userdata-folder there. Giving Bridge admin rights resolved it. But moving the extension to Per-user extension folder (`C:\Users\<USERNAME>\AppData\Roaming\Adobe\CEP\extensions`) also resolved it.

@stuomas Maybe an idea to add a message about "No rights to create userdata-folder"? 

For the rest, thanks for development, any plans/roadmap for this extension?

**Comment by stuomas** [comment]
Hi @igorrust and thanks for debugging this :)

Some error message is definitely a good idea, it shouldn't fail silently.

I don't have any roadmap for this. I'm not happy with the user experience of the installation step, but I don't see any easy way around it, but that would be definitely first thing to fix if I ever find energy to research that.

Functionality-wise it feels OK to me. Do you have some development ideas?

**Comment by igorrust** [comment]
> Functionality-wise it feels OK to me. Do you have some development ideas?
At the moment nothing specific.  I was surprised that a tool like Bridge didn't include a map view, so it's nice to see that someone else jumped in. 

I'm not sure what the possibilities are with regards to these extensions. Bulk edit of photos to assign them to a location, and dragging the pins over the map to relocate them (with possibly auto-update the location coordinates) is something that pops-up now in my mind. 

I also noticed my search option didn't work, but I can spend some time later to have a better look.

**Comment by stuomas** [comment]
It's also mine one and only extension I've worked with, and it was a while ago I worked with this, so I don't really remember what the possibilities are either.

If you mean by bulk edit that selecting multiple photos and tagging them in same location, that should work already.
And you can always place a new location marker to relocate them (not by dragging the old marker, though).

The missing search functionality might be a permissions issue with the API key. I've documented that you need to enable `Maps JavaScript API` and `Places API` but it's possible I forgot something if those are not sufficient.

**Comment by stuomas** [comment]
I added some error handling and updated README. Thanks for reporting @igorrust !
